deepspeed_config:
 deepspeed_config_file: /datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2/llm_decoder/config/maira2/ds_config/stage_2.json
 zero3_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
use_cpu: false
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false
