defaults:
  - //datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2/cxrmate2/config/000_sft.yaml@_global_
  - _self_

num_nodes: 1

stages_module: /datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2/cxrmate2/stages_cxrmate2_dpo_lora.py

other_exp_dir: /datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2/experiments_scratch/cxrmate2/final/002_grpo_rev_a

beta: 0.2  # Higher → Less policy drift.

num_epochs: 16

max_train_prompt_len: 1024

train_mbatch_size: 1
val_mbatch_size: 1
test_mbatch_size: 1

optimiser_kwargs:
  lr: 1e-5
  amsgrad: False
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0.01
num_cycles: null

log_loss_every_n_steps: 10

generated_reports: /datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2/cxrmate_ms_retro_stage_1/data/generated_reports.csv

# upload_ckpt_dir: /datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2/experiments_scratch/cxrmate2/final/001_grpo/trial_5/epoch=1_val_findings_ratescore_ratescore=0.7427/evaluate
# hf_hub_alias: aehrc/cxrmate-2

# LoRA:
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05

enable_gradient_checkpointing: false

test_datasets: 
  - mimic_cxr_dpo
  - chexpert_plus
  - rexgradient