defaults:
  - //datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2/cxrmate2/config/clusters/amdgpu/8gpu.yaml@_global_
  - _self_

one_epoch_only: false
interim_checkpointing: false
submit_evaluation: false

time_limit: '7-00:00:00'

cluster_manager_options: [[account, OD-232446], [partition, amdgpu]]

cluster_manager_script_commands: [
  cd /datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2,
  module load apptainer, 
  IMAGE_PATH=/scratch3/nic261/images/rocm_pytorch-training_v25.4.sif, 
  ACCELERATE_EXEC_PATH=/scratch3/nic261/environments/cxrmate2_amdgpu_final/bin/accelerate,
  'export APPTAINER_BINDPATH="/datasets,/scratch3"',
  'export HIP_FORCE_DEV_KERNARG=1',
  'export NCCL_MIN_NCHALLENS=112',
  'export TORCH_BLAS_PREFER_HIPBLASLT=1',
  'export PYTORCH_ROCM_ARCH=gfx942',
]
accelerate_exec_path: "apptainer exec $IMAGE_PATH $ACCELERATE_EXEC_PATH"
venv_path: /scratch3/nic261/environments/cxrmate2_amdgpu_final/bin/activate
