defaults:
  - //datasets/work/hb-mlaifsp-mm/work/repositories/25_cxrmate2/clusters/virga/4gpu.yaml@_global_
  - _self_

prefetch_factor: 2

srun_options: -u
cluster_manager_options: [[account, OD-232446]]

exp_dir: /scratch3/nic261/experiments
database_dir: /scratch3/nic261/database/cxrmate_ed
email: aaron.nicolson@csiro.au

long_term_exp_dir: /datasets/work/hb-mlaifsp-mm/work/experiments
ignore_extensions: [.distcp, .metadata, .pkl]

one_epoch_only: true

log_loss_every_n_steps: 50
